### ISSUE TITLE
No Purchase-Other operations are retrieved after a certain date

### ISSUE THREAD

**Issue by louim-lbs** [dhojayev/traderepublic-portfolio-downloader#44]
**Describe the bug**

No **Purchase-Other** operations are retrieved after 3rd of June, 2024, tough their **Dividends** and **Purchase-Cryptocurrency** operations are.

**To Reproduce**

Use the executable following Readme instructions.

**Expected behavior**

Every transaction is retrieved.

**Desktop (please complete the following information):**

 - OS: W11
 - Version: 0.13

**Additional context**

In the logs I have:

`[INFO] Transactions total: 877; completed: 452; skipped: 425`

The skipped ones could be the one I am looking for. They are apparently skipped because:

`[WARN] [id:************] Unsupported transaction skipped`

Are they maybe unsupported because the pdf are in French?

Thanks!

**Comment by dhojayev** [comment]
Hey @louim-lbs ,
Thanks for your report. 
Can you please follow these steps and post the results here?

https://github.com/dhojayev/traderepublic-portfolio-downloader/issues/43#issuecomment-2395374832

**Comment by louim-lbs** [comment]
Thanks for your quick answer!

Here what I understood from the timelineTransactions logs:
- Recognized operation are `"eventType": "SAVINGS_PLAN_EXECUTED",`
- Not recognized ones are `"eventType": "SAVINGS_PLAN_INVOICE_CREATED",`

An example of timelineDetailV2 log for a not recognized operation:

```{
  "id": "********-****-****-****-************",
  "sections": [
    {
      "action": {
        "payload": "US023135****",
        "type": "instrumentDetail"
      },
      "data": {
        "icon": "logos/US023135****/v2",
        "status": "executed",
        "subtitleText": null,
        "timestamp": "2024-10-09T15:20:39.847+0000"
      },
      "title": "Du hast 1,00 € investiert",
      "type": "header"
    },
    {
      "action": null,
      "data": [
        {
          "detail": {
            "functionalStyle": "EXECUTED",
            "text": "Ausgeführt",
            "type": "status"
          },
          "style": "plain",
          "title": "Status"
        },
        {
          "detail": {
            "action": null,
            "text": "Sparplan",
            "trend": null,
            "type": "text"
          },
          "style": "plain",
          "title": "Orderart"
        },
        {
          "detail": {
            "action": null,
            "text": "Amazon.com",
            "trend": null,
            "type": "text"
          },
          "style": "plain",
          "title": "Asset"
        },
        {
          "detail": {
            "icon": "logos/bank_traderepublic/v2",
            "text": "Guthaben",
            "type": "iconWithText"
          },
          "style": "plain",
          "title": "Zahlung"
        }
      ],
      "title": "Übersicht",
      "type": "table"
    },
    {
      "action": null,
      "data": [
        {
          "detail": {
            "action": {
              "payload": {
                "savingsPlanId": "********-****-****-****-************"
              },
              "type": "openSavingsPlanOverview"
            },
            "amount": "1,00 €",
            "icon": "logos/US023135****/v2",
            "status": "executed",
            "subtitle": "Wöchentlich",
            "timestamp": "2024-10-09T15:20:39.847Z",
            "title": "Amazon.com",
            "type": "embeddedTimelineItem"
          },
          "style": "plain",
          "title": ""
        }
      ],
      "title": "Sparplan",
      "type": "table"
    },
    {
      "action": null,
      "data": [
        {
          "detail": {
            "action": null,
            "text": "0,005941",
            "trend": null,
            "type": "text"
          },
          "style": "plain",
          "title": "Anteile"
        },
        {
          "detail": {
            "action": null,
            "text": "168,30 €",
            "trend": null,
            "type": "text"
          },
          "style": "plain",
          "title": "Anteilspreis"
        },
        {
          "detail": {
            "action": null,
            "text": "Gratis",
            "trend": null,
            "type": "text"
          },
          "style": "plain",
          "title": "Gebühr"
        },
        {
          "detail": {
            "action": null,
            "text": "1,00 €",
            "trend": null,
            "type": "text"
          },
          "style": "highlighted",
          "title": "Gesamt"
        }
      ],
      "title": "Transaktion",
      "type": "table"
    },
    {
      "action": null,
      "data": [
        {
          "action": {
            "payload": "****",
            "type": "browserModal"
          },
          "detail": "09.10.2024",
          "id": "********-****-****-****-************",
          "postboxType": "SAVINGS_PLAN_EXECUTED_V2",
          "title": "Abrechnung Ausführung"
        }
      ],
      "title": "Dokumente",
      "type": "documents"
    }
  ]
}```

Do you need the full operation logs?

**Comment by dhojayev** [comment]
Great, thanks!
I would also need the contents of these:
Recognized operation are "eventType": "SAVINGS_PLAN_EXECUTED",
Not recognized ones are "eventType": "SAVINGS_PLAN_INVOICE_CREATED",

Of course with private data removed.

**Comment by louim-lbs** [comment]
Here it is, two consecutive exemple from page-x.json:

```    {
      "action": {
        "payload": "********-****-****-****-************",
        "type": "timelineDetail"
      },
      "amount": {
        "currency": "EUR",
        "fractionDigits": 2,
        "value": -0.999886
      },
      "badge": null,
      "eventType": "SAVINGS_PLAN_INVOICE_CREATED",
      "icon": "logos/US0231351067/v2",
      "id": "********-****-****-****-************",
      "status": "EXECUTED",
      "subAmount": null,
      "subtitle": "Sparplan ausgeführt",
      "timestamp": "2024-10-16T14:55:20.954+0000",
      "title": "Amazon.com"
    },
    {
      "action": {
        "payload": "********-****-****-****-************",
        "type": "timelineDetail"
      },
      "amount": {
        "currency": "EUR",
        "fractionDigits": 2,
        "value": -0.999881
      },
      "badge": null,
      "eventType": "SAVINGS_PLAN_INVOICE_CREATED",
      "icon": "logos/US67066G1040/v2",
      "id": "********-****-****-****-************",
      "status": "EXECUTED",
      "subAmount": null,
      "subtitle": "Sparplan ausgeführt",
      "timestamp": "2024-10-16T14:44:39.987+0000",
      "title": "NVIDIA"
    },```

**Comment by dhojayev** [comment]
Perfect. I will implement the support for it. 
For now this is all I need. Thank you!

**Comment by dhojayev** [comment]
Hey @louim-lbs,
I have good news: I implemented support for these transactions.
Please download a binary for your system, run it and let me know if it works:
https://github.com/dhojayev/traderepublic-portfolio-downloader/actions/runs/11442768956

If there are more transactions missing - you could create a new issue to implement them. You can follow the same steps to get the raw responses.

Please let me know then if it works and I can proceed with the release.
Thanks!

**Comment by louim-lbs** [comment]
Hey @dhojayev,
Thank you very much, it works well!
Though we can close this specific issue, I still see some missing transactions. I'll open a new one about it.
